### PR TITLE
fix some stroke:#000 occurrences

### PR DESCRIPTION
**Pull request by mawinter69**
there are 3 files that still had stroke:#000 instead of stroke:currentColor

### Testing done

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Review by timja — APPROVED** [review]
FWIW the ionic team have suggested we fix this in l:icon itself as thats how they do it via CSS attributes so they don't have to do what we're doing

**Comment by mawinter69** [comment]
> FWIW the ionic team have suggested we fix this in l:icon itself as thats how they do it via CSS attributes so they don't have to do what we're doing

Not sure what you exactly mean, but if a symbol is more than just some lines in a single color it might have side-effects when applying styles unconditionally.

**Comment by timja** [comment]
see https://github.com/ionic-team/ionicons/issues/1129#issuecomment-1295027543.

I wonder if there'd be a way to add it for just ionicons.

**Comment by mawinter69** [comment]
afaik all icons in here have `class="ionicon"`  (to be verified)

**Pull request merged**
