### PR TITLE
Update icons to be themeable

### PR DESCRIPTION
**Pull request by strangelookingnerd**
In order to fix https://github.com/jenkinsci/custom-folder-icon-plugin/issues/93 I went over most of the icons and added missing `fill="currentColor"` attributes if they were missing. I might have become snow-blind doing this so sorry if I missed something.

Here is a preview of the icons in white and dark theme:

image
image

I was unsure whether to create this PR here or directly in https://github.com/ionic-team/ionicons - let me know what works best for you.

### CODE REVIEW

**Comment by timja** [comment]
> I was unsure whether to create this PR here or directly in [ionic-team/ionicons](https://github.com/ionic-team/ionicons) - let me know what works best for you.

Ideally both, they haven't been very responsive to pull requests though, but would be good to at least submit it there.

Thanks for the change!

**Review by timja — APPROVED** [review]

**Comment by NotMyFault** [comment]
> Ideally both, they haven't been very responsive to pull requests though, but would be good to at least submit it there.

Historically, I submitted all fixes to ionicons we addressed in core, but none of them received feedback by now, that would allow us to get further with it.

I'm fine with fixing issues here, and potentially adding more symbols 👍🏻

**Comment by timja** [comment]
> I'm fine with fixing issues here, and potentially adding more symbols 👍🏻

I'm unsure about new ones being in here, if we want some custom specific ones they should go in the plugin related to them.
If they're reusable there could be a shared one.

**Comment by NotMyFault** [comment]
> if we want some custom specific ones they should go in the plugin related to them

Agreed. The Jenkins icon I added is a general purpose symbol, but generally I don't think we need to add any symbol, unless they directly relate to this project.

**Pull request merged**
